### ISSUE TITLE
Add drag and drop for routes

### ISSUE THREAD

**Issue by warpech** [Starcounter/Website#195]
Depends on #194 

## Problem

It is not possible to change the order of routing.

## Proposed solution

Add a drag and drop feature (using `juicy-draggable`) to change the order of routing. 

Each route should have an `Order` property. 

When the route is dragged above or below another route, their orders should be swapped.

This should not only affect the display order but also the actual routing. WebsiteProvider should apply the first route from the top of the page that matches the URI.

**Comment by PatrykSzwer** [comment]
Moved to: https://github.com/Starcounter/Blending/issues/17
