### ISSUE TITLE
Select Blend URI option

### ISSUE THREAD

**Issue by Mihaiii** [Starcounter/Website#234]
In Content app I use the id for URIs (ex: `/content/dynamic/Cq`).

In version 1 of Content app, the user had the possibility to write the URIs that he/she desires (after `/content/dynamic/`), but I changed this because now a Content Item can have a `Name` and there can be multiple Content Items with the same name (especially if the parent content item is different. For example, "Introduction" can be a content item name that is repeating).

So at this moment the user has to select the URI that is provided when he/she creates a new content item and copy it to "Blend URI". I don't find this very friendly.

I was thinking about having a combo box for Blend URI, maybe? (with displays like `/content/dynamic/Cq ({ContentItemName})` if the values are from `Simplified.Ring6.WebContent`)
What do you think?

**Comment by warpech** [comment]
I support this idea, I was thinking about it for a long time. We will add it in one of the future releases.

**Comment by PatrykSzwer** [comment]
Moved to https://github.com/Starcounter/Blending/issues/10
