### ISSUE TITLE
Two tests failing

### ISSUE THREAD

**Issue by warpech** [Starcounter/Website#237]
Since Oct 13th [one test in WebsiteProvider are consistently failing](http://teamcity.starcounter.org/viewType.html?buildTypeId=Apps_Website_Develop) (in both tested browsers):

```
BlendingRulesMappingTests(Chrome).RequestPage_BlendingRulesNotDefinedForRoute_TheBlendingContentLoaded
BlendingRulesMappingTests(Firefox).RequestPage_BlendingRulesNotDefinedForRoute_TheBlendingContentLoaded
```

With the error:

```
 Expected: 2 But was: 0 at WebsiteProvider.Tests.Test.BlendingRulesMappingTests.RequestPage_BlendingRulesNotDefinedForRoute_TheBlendingContentLoaded() in C:\TeamCity\BuildAgent\work\345281ad5dc7c0da\Website\test\WebsiteProvider.Tests\Test\BlendingRulesMappingTests.cs:line 96
```

@alemoi is this something you can investigate directly? Do you need any help to reproduce it? I assume the tests are quite straightforward but in case you can't read them please contact me.

**Comment by alemoi** [comment]
Yeah, I was trying to investigate it but having troubles understanding why the Website app is mapping and unmapping URIs all the time: https://github.com/Starcounter/level1/pull/4294#issuecomment-336599246
I need some help from @un-tone I suppose. Or who is the author of Website app?

**Comment by warpech** [comment]
Yes, the current maintainer of WebsiteProvider is @un-tone.

**Comment by warpech** [comment]
@un-tone has created a temporary fix for this in https://github.com/Starcounter/Website/commit/d94e66f7f7ec98f390e1e61d48edf94982265166, but we decided to not implement it and remove this feature.

This is tracked in https://github.com/Starcounter/Website/issues/247
