### ISSUE TITLE
Visual improvements for WebsiteEditor

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Website#239]
After long discussion with @warpech, We decided to make few small changes to improve user experience for Website Editor app:

1. Rename unassigned surfaces to ungrouped surfaces.
2. Make iframe for preview wider so that holy grail looks correct, and make Preview header as a link to new window.
3. Rename Route URI in blending rules to route.
4. Fix Route URI (in Blending rules) content - add headers from routes view.
5. Replace green + button for adding surface with more intuitive "add surface" button placed on the end of surfaces.
6. Merge "URI" and "Headers" in route header.
7. Rename Route nesting enabled to Surface nesting in route header.
8. First name in Route URI in blending point should be "All Routes"

**Comment by warpech** [comment]
Closing as done in #241
