### ISSUE TITLE
Remove the support for executing blending rules for the default blending point

### ISSUE THREAD

**Issue by warpech** [Starcounter/Website#247]
For the reasons explained in:

- https://github.com/Starcounter/Website/issues/237 (two tests fail after `Blender.MapUri` improvements)
- https://github.com/Starcounter/Website/issues/238 (WebsiteProvider uses costly calls to `Blender.MapUri` and `Blender.UnmapUri` at runtime in middleware)

We decided to do the following:

1. remove the feature of blending additional content to the "default blending point"
    - remove the code in WebsiteProvider that does that
    - change the current tests in WebsiteProvider to check that it does NOT work
2. whenever a user tries to set a blending rule to the default blending point in WebsiteEditor, we will show a warning that blending rules cannot be added to the default blending points.
    - I imagine this can be a warning sign with the description in a tooltip
    - a user can still define such blending rule, it will just not work

@PatrykSzwer please implement the changes in WebsiteEditor and WebsiteProvider. @un-tone will review both.

**Comment by PatrykSzwer** [comment]
Done, closing.
