### ISSUE TITLE
Create a Settings page with Reset, Import and Export

### ISSUE THREAD

**Issue by warpech** [Starcounter/Website#251]
Create a settings page with the following options:

- "Delete all surfaces" button that opens a modal with
    - text "This will delete all surfaces, blending points, blending rules and routes" 
    - OK button
    - Cancel button
- "Import data from sqlite3 file" file upload
    - uses `StarDump.exe unload --database <current database name> --file WebsiteEditorConfig.sqlite3 --reassignobjectno --forcereload` to reload the file to the database
- "Export data to a sqlite3 file" button that downloads the configuration
    - uses `StarDump.exe unload --database <current database name> --file WebsiteEditorConfig.sqlite3 --unloadtables Starcounter.HTMLComposition,Simplified.Ring6.WebContent,Simplified.Ring6.WebHttpHeader,Simplified.Ring6.WebMap,Simplified.Ring6.WebSection,Simplified.Ring6.WebTemplate,Simplified.Ring6.WebTemplateGroup,Simplified.Ring6.WebUrl,Simplified.Ring6.WebUrlProperty`

See https://github.com/Starcounter/RebelsLounge/issues/184 for details about how to use stardump for blending config import/export.

**Comment by un-tone** [comment]
Please be aware that I also started to work on settings page in according to https://github.com/Starcounter/Website/pull/211#issuecomment-337258805 (`47_viewkeeper-settings` branch). But currently I'm blocked by the https://github.com/Starcounter/Website/issues/252 issue which should be escalated, I assume.

**Comment by PatrykSzwer** [comment]
Closing as done.
