### ISSUE TITLE
Fix authorization library using

### ISSUE THREAD

**Issue by un-tone** [Starcounter/Website#252]
Current implementation doesn't let simply add another page types - it works well only for ones implementing `IKnowSurfacePage`.

Also it is incorrect re-creating of `CurrentPage` here https://github.com/Starcounter/Website/blob/16beaa01bbbf241dceb1a23c48c37728d0774224/src/WebsiteEditor/Api/Authorization/MasterPageMiddleware.cs#L42 since it already assigned in the code a little above https://github.com/Starcounter/Website/blob/16beaa01bbbf241dceb1a23c48c37728d0774224/src/WebsiteEditor/Api/Authorization/MasterPageMiddleware.cs#L25

Moreover this code looks redundant since we use authorization library components https://github.com/Starcounter/Website/blob/33e85a23e3dd443d42f310d766469bc36a1b3ff6/src/WebsiteEditor/Api/MainHandlers.cs#L80-L86

**Comment by warpech** [comment]
Is this something that @PatrykSzwer can fix in WebsiteEditor or is it a fault of the Authorization library?

**Comment by PatrykSzwer** [comment]
I can try to partly fix it, but I can't promise that I can handle all of this problems.

**Comment by PatrykSzwer** [comment]
Closing as done.
