### ISSUE TITLE
Creating new blending point in TopbarSurface throws exception

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Website#254]
### Steps to reproduce
1. Login as admin user.
2. Run SignIn, WebsiteEditor and WebsiteProvider.
3. Go to http://localhost:8080/WebsiteEditor
4. Choose TopbarSurface.
5. Go to blending points tab.
6. Create new blending point, give it any name and click Save.
7. Click on General tab or `Back to groups

### Expected result
No errors

### Actual result
Internal server error is thrown.

**Comment by un-tone** [comment]
Closing as fixed.
