### ISSUE TITLE
Generate the DOM part of the surface views automatically

### ISSUE THREAD

**Issue by warpech** [Starcounter/Website#255]
One of the remaining weak points of WebsiteEditor & WebsiteProvider is that your surface needs a static HTML file that represents a view of that surface. For example: https://github.com/Starcounter/Website/blob/6c5d6ececa62b28a8a242cec14351893215970a3/src/WebsiteProvider/wwwroot/WebsiteProvider/surfaces/TopbarSurface.html

This file should be created on the fly by a handler that returns something like this:

```html
<link rel="import" href="/sys/polymer/polymer.html">
<template>
    <template is="dom-bind">
        <starcounter-include slot="websiteeditor/topbar" view-model="{{model.Sections.Topbar}}" class="website-topbarsurface-topbar"></starcounter-include>
        <starcounter-include slot="websiteeditor/main" view-model="{{model.Sections.Main}}"></starcounter-include>
    </template>
    <template is="declarative-shadow-dom">
        <slot name="websiteeditor/topbar"></slot>
        <slot name="websiteeditor/main"></slot>
    </template>
</template>
```

Everything that is a difference between the above snippet and the current content of https://github.com/Starcounter/Website/blob/6c5d6ececa62b28a8a242cec14351893215970a3/src/WebsiteProvider/wwwroot/WebsiteProvider/surfaces/TopbarSurface.html should be a **custom composition** that is stored in the database like a custom composition of any other view of a Starcoutner app.

@PatrykSzwer can you try to prototype this? We can discuss this in person in more detail.

**Comment by PatrykSzwer** [comment]
Closing as done. 🎆 🎉
