### ISSUE TITLE
Apply agreed project structure

### ISSUE THREAD

**Issue by warpech** [Starcounter/Website#258]
The project structure does not adhere to our own guidelines presented at https://docs.starcounter.io/cookbook/project-structure/

What I mean:

- folder `src/WebsiteEditor/wwwroot/WebsiteEditor/viewmodels` should be renamed to `views`
- perhaps something else? (please check)

This is low prio.

**Comment by PatrykSzwer** [comment]
Closing as done.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/Website/releases/tag/4.1.0
