### ISSUE TITLE
Spaces doesn't work in inputs inside paper-collapse-item

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Website#259]
When You try to write space inside any input from paper-collapse-item (e.g add space inside blending point name) nothing is going to happen. It's related to bug in paper element itself, which can be followed here: https://github.com/PolymerElements/paper-item/issues/28 and https://github.com/Collaborne/paper-collapse-item/issues/19 here.

I've tried to implement workaround mentioned here https://github.com/Collaborne/paper-collapse-item/issues/19#issuecomment-338905929 but without results. I'll keep trying to do it later, if they don't fix this issue in element itself.

**Comment by PatrykSzwer** [comment]
This was done in #291.  Closing.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/Website/releases/tag/4.1.0
