### ISSUE TITLE
Can't log in on /signin/signinuser page

### ISSUE THREAD

**Issue by un-tone** [Starcounter/Website#265]
### Steps to reproduce

1. Run **SignIn** app from `develop` branch.
1. Run **WebsiteEditor** and **WebsiteProvider** apps from `develop` branch.
1. Log out and go to <http://localhost:8080/signin/createadminuser>.
1. Create the "admin" user if needed.
1. Press "BACK" button so you go to <http://localhost:8080/signin/signinuser> page.
1. Input the credentials and press "Sign In" button.

### Expected result

The page refreshed and user is authorized.

### Actual result

Nothing is happened, the button only becomes disabled. The user is still not authorized.

### Screenshot

![image](https://user-images.githubusercontent.com/1625378/32492660-268439f2-c3cc-11e7-8585-8c7102a4dd86.png)

### Notes

* It works well without running WebsiteProvider
* If you go to <http://localhost:8080/signin/signinuser> directly it works well.

**Comment by Mihaiii** [comment]
Like https://github.com/Starcounter/Website/issues/264 (as @PatrykSzwer mentioned), this issue is no longer reproducible with latest RC that uses latest `palindrom-redirect`.

I hope this message saved you some time. 👍

**Comment by un-tone** [comment]
Confirm. The issue is not reproducible in SC 2.3.1.7786. Closing...

**Comment by un-tone** [comment]
Thank you @Mihaiii
