### ISSUE TITLE
Smooth permanent deleting surfaces

### ISSUE THREAD

**Issue by un-tone** [Starcounter/Website#267]
Based on the comment https://github.com/Starcounter/Website/issues/200#issuecomment-341848568:

1. user clicks the "Delete" button, which deletes the surface
2. this triggers a delete commit hook in WebsiteProvider
2. WebsiteProvider unmaps the surfaces before deleting
3. WebsiteProvider repeats the function https://github.com/Starcounter/Website/blob/a69aa8b94c11bb94806416b224a2b40974e87343/src/WebsiteProvider/Api/ContentHandlers.cs#L79 for all current sessions. This should remove the surface from being used because it is unmapped now
4. now the surface can be safely deleted

**Comment by PatrykSzwer** [comment]
Moved to https://github.com/Starcounter/Blending/issues/12
