### ISSUE TITLE
Add View Keeper settings on Settings page

### ISSUE THREAD

**Issue by un-tone** [Starcounter/Website#268]
Currently View Keeper settings configuring implemented through administrative URIs (https://github.com/Starcounter/Website/pull/211#issuecomment-341066322).

Here we should remove it and add "Enable View Keeper" checkbox on the WebsiteEditor's Settings page.

**Comment by PatrykSzwer** [comment]
Since view keeper functionality is already merged to develop, and https://github.com/Starcounter/Website/pull/262 has to wait for stardump changes, I'll implement this part there.

**Comment by PatrykSzwer** [comment]
Closing as done.
