### ISSUE TITLE
Exception when clicking general tab two times

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Website#273]
### Steps to reproduce
1. Go to http://localhost:8080/WebsiteEditor/surfacegroups and choose responsive or sidebar surface.
2. You will be at surface's general tab.
3. Click "General" on navigiation bar again.
### Expected result
Nothing happen.
### Actual result
You will get an error:
![image](https://user-images.githubusercontent.com/25042256/32838394-0c540d64-ca11-11e7-9870-d661f01cedbf.png)

##### Starcounter version 2.3.1.7772

**Comment by un-tone** [comment]
I can't reproduce it in SC 2.3.1.7771

**Comment by un-tone** [comment]
Did it. It is reproducible on nested pages.

**Comment by PatrykSzwer** [comment]
I just wanted to write that, that reproduction can be done on responsive surface and sidebar surface.

**Comment by Mihaiii** [comment]
Can't reproduce with SC 2.3.1.7779

**Comment by un-tone** [comment]
It's still reproducible in SC 2.3.1.7786

**Comment by Mihaiii** [comment]
I still can't reproduce it with that SC version so I suppose I'm doing something wrong.
Sorry for misinforming :).

**Comment by warpech** [comment]
I have removed the label "P/Low" because we should only use the project board. In fact, I think this is of high priority because nested surfaces are a common scenario.

**Comment by un-tone** [comment]
Created PR #276

**Comment by un-tone** [comment]
Closing as done
