### ISSUE TITLE
Move holygrail.css from WebsiteProvider

### ISSUE THREAD

**Issue by un-tone** [Starcounter/Website#278]
This file should be moved [WebsiteEditor/wwwroot/WebsiteEditor/css/holygrail.css](https://github.com/Starcounter/Website/blob/master/src/WebsiteEditor/wwwroot/WebsiteEditor/css/holygrail.css) because this file is not accessible in the case when WebsiteEditor is not running.

**Comment by PatrykSzwer** [comment]
Closing as done.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/Website/releases/tag/4.1.0
