### ISSUE TITLE
Data manipulation methods should be inaccessible for unauthorized users 

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Website#279]
Right now user doesn't have to be admin or even logged in to use Uri's/methods like `/resetdata` or `/cleardata`. Those are really crucial and only administrator should be able to use them.

**Comment by PatrykSzwer** [comment]
Closing as done.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/Website/releases/tag/4.1.0
