### ISSUE TITLE
Import and export data should have more informative messages

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Website#280]
Right now, import and export actions have only "Successful" message available. It's clearly not enough and we have to show what actually happens in console, when something went wrong. I'll add information from console output to message box whenever something wrong happen.

**Comment by PatrykSzwer** [comment]
Closing as done.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/Website/releases/tag/4.1.0
