### ISSUE TITLE
⏰ WebsiteEditor and WebsiteProvider doesn't work on Starcounter 2.4

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Website#284]
Right now there is no possibility to run Website under Starcounter 2.4. We have to:

1. Create new branch, `master-2.4`
2. Add compatibility attribute.
3. Biggest issue why website is not building is missing of `Simplified`. I think the easiest way right now, will be to somehow import `Simplified` as a dll to solution.

**Comment by PatrykSzwer** [comment]
Actually I have some concerns about pt. 3.
What is our policy in importing `Simplified` to SC 2.4 project? Can I just import entire `.dll` file, or should I separate used classes into separated database classes to solution? And what about correlation between provider and editor, since them are using same classes. I assume that when I copy classes 2 times for both projects, they will NOT share data. What is the solution for that since we don't have mapping yet?

**Comment by per-samuelsson** [comment]
> What is our policy in importing Simplified to SC 2.4 project?

The "correct" way would be to start distribute Simplified as a NuGet package, and have all apps that depend on it use that package.

Seem though like the currently promoted way would be https://github.com/StarcounterApps/Simplified#adding-simplified-to-your-project.

**Comment by PatrykSzwer** [comment]
I've added recently created package with Simplified made by @habib535. Still, I can't run website properly. I'm getting error warnings like:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The debug sequence failed. Consult the Visual Studio error list for more information. HTTP/1.1 500 InternalServerError
Server: Starcounter/2.4.0.3938 (Windows)
Date: Thu, 23 Nov 2017 15:59:52 GMT
Cache-Control: no-store
Content-Length: 301

{"Text":"ScErrDatabaseAlreadyExists (SCERR2047): A database with the specified name already exists. Can't register new codehost \"default. Version: 2.4.0.3938. Help page: https://docs.starcounter.io/?q=SCERR2047. ","ServerCode":2047,"Helplink":"https://docs.starcounter.io/?q=SCERR2047","LogEntry":""} (ScErrDebugFailedReported (SCERR12012))
```
I've removed default database (created under 2.3.1) and created new one, and still got this error.

**Comment by habib535** [comment]
This seems to be a bug in Star v2.4

I just created a class library and referenced it in the Starcounter application.
`SELECT * FROM StarcounterClassLibrary1.Entity1`
works fine in v2.3 but gives error `Unknown class StarcounterClassLibrary1.Entity1` in 2.4

![image](https://user-images.githubusercontent.com/2991381/33183969-8b409196-d07a-11e7-9200-600756a84d1b.png)

**Comment by PatrykSzwer** [comment]
You mean that this can be related to Your `Simplified` nuget package and some 2.4 bug? Could You please report that?

**Comment by habib535** [comment]
@PatrykSzwer please try updating the nuget package to `1.0.1`, this should fix the issue.

**Comment by PatrykSzwer** [comment]
Thanks @habib535, looks like it helped! But not everything is working yet.

Right now Website is building and running properly, but when I try to go to `/websiteeditor` I'm getting exception like this:
![image](https://user-images.githubusercontent.com/25042256/33319331-6ee99d2c-d43e-11e7-8da4-5f4bbc806106.png)

Seems like It's related with authorization library. @joozek78 could You please take a look?

**Comment by PatrykSzwer** [comment]
Seems like problem occurs because of differences in weaving between 2.3 and 2.4, more specific because 
for 2.3 libraries are weaved in run time and for 2.4 in build time. There is a nice warning about this in VS:
 
![image](https://user-images.githubusercontent.com/25042256/33369686-aaf759f0-d4f5-11e7-921b-324dec94298f.png)

@per-samuelsson Do You know how could we deal with this problem?

**Comment by joozek78** [comment]
The obvious solution is to release a new version of the library, targetting `2.4`. The tough question is can we avoid releasing a new version of the library just because we changed binary compatibility. Maybe we could defer weaving of libraries until an app using them is built? Maybe just "test-weave" them to verify the will not pose any problems?

**Comment by per-samuelsson** [comment]
> @per-samuelsson Do You know how could we deal with this problem?

None else than what @joozek78 propsed I'm afraid:

> The obvious solution is to release a new version of the library, targetting `2.4`.

I wrote it several times already when we switch from boot-time to compile-time weaving in 2.4, that it was going to be quite a big change that would need to be considered in most deployment scenarios, and now we are there.

**Comment by per-samuelsson** [comment]
> Maybe we could defer weaving of libraries until an app using them is built? Maybe just "test-weave" them to verify the will not pose any problems?

I'm really glad to see creative suggestions like that. But I don't think we want to go there. Then we have even more code to maintain, and more possible problem-areas. I really think we need to just accept the fact that we have changed how apps and libraries are built between these versions, and adapt to it in most straight-forward way, on app-level. Not changing platform again.

**Comment by per-samuelsson** [comment]
FWIW, it is possible using low-level tooling to weave assemblies "on the fly":

```
scweaver Starcounter.Authorization.dll
```

Maybe that could be usable somehow?

**Comment by joozek78** [comment]
We could incorporate it into the build as a workaround. I'm currently writing response tackling the issue at large

**Comment by joozek78** [comment]
>Then we have even more code to maintain, and more possible problem-areas

what do you mean? I propose to weave only when building an executable. What are the potential problems?

> adapt to it in most straight-forward way, on app-level

It would be fine if it remained at app level. Unfortunately, it means that anyone who wants to release a library - and we want people to do it - has to rebuild and re-release it every time Starcounter issues a binary-incompatible release. Imagine the following scenario:

1. Mopedo created a library called Dynamit. It's quite useful. They released it on NuGet as 1.0.0, weaved for Starcounter 2.4.0
1. Patryk uses it in his project with 2.4.0
1. Starcounter releases binary-incompatible (yet otherwise compatible) 2.4.1
1. Marcin wants to use Dynamit in his project on 2.4.1, so Mopedo releases a new version (1.1.0) on NuGet, targeting 2.4.1
1. Patryk spots a bug in Dynamit and Mopedo is happy to fix it. The only problem is that they need to support two "release branches" with identical code, but using different weavers. They realize it's too hard to maintain a library and abandon the project :(

**Comment by mmnosek** [comment]
> They realize it's too hard to maintain a library and abandon the project :(

This is really bad and we should avoid it at all costs, really!

**Comment by per-samuelsson** [comment]
> This is really bad and we should avoid it at all costs, really!

Of course.

> what do you mean? I propose to weave only when building an executable. What are the potential problems?

I probably misunderstood your intent. I thought you meant we should redesign the platform somehow. Weaving when building assemblies that target Starcounter is exactly what 2.4 is all about, so of course no problem with that.

> [...] it means that anyone who wants to release a library - and we want people to do it - has to rebuild and re-release it every time Starcounter issues a binary-incompatible release.

Well, just as we can't tamper with our public API's, we need to pay as close attention to when we change Starcounter facade consumed by the weaver. Public APIs and weaver facade kind of have to go hand in hand. If any of them change in an incompatible way, you have to rebuild your application.

The only way to solve this is to aim at always being backwards compatible. At least I don't know of any other way.

This is all nothing new though. The only thing that has changed in 2.4 is that weaver-targeting APIs need to stay compatible, which is some extra burden, but solely on us. For public APIs, it's always been that way.

**Comment by warpech** [comment]
Please let's put the focus on fixing WebsiteEditor and WebsiteProvider in Starcounter 2.4. This is urgent for @Starcounter/sc-apps.

cc @LarsTjernstrom, @Mihaiii 

The list of remaining issues AFAIK:

- [ ] Response handlers is not working in SC 2.4 (https://github.com/Starcounter/Home/issues/338)

**Comment by PatrykSzwer** [comment]
>FWIW, it is possible using low-level tooling to weave assemblies "on the fly":
scweaver Starcounter.Authorization.dll
Maybe that could be usable somehow?

I've tried to use that and currently I'm getting an error:
```
System.Exception: ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver.
Version: 0.0.0.
Help page: https://docs.starcounter.io/?q=SCERR6066. ---> PostSharp.Sdk.CodeModel.BindingException: Cannot find a field named 'Getter' of type '[mscorlib]System.Func`2<Starcounter.Json,Starcounter.Arr`1<!0>>' in scope 'Starcounter.Templates.TArray`1' (module = 'Starcounter.XSON.dll').
   at PostSharp.Sdk.CodeModel.Collections.FieldDefDeclarationCollection.GetField(String name, ITypeSignature type, BindingOptions bindingOptions)
   at PostSharp.Sdk.CodeModel.FieldRefDeclaration.GetFieldDefinition(BindingOptions bindingOptions)
   at PostSharp.Sdk.Extensibility.Tasks.IndexGenericInstancesTask.Execute()
   at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)
   at PostSharp.Hosting.PostSharpObject.ExecuteProjects()
   at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)
   at Starcounter.Weaver.CodeWeaver.Execute() in C:\TeamCity\BuildAgent\work\sc-11273\Level1\src\Starcounter.Weaver\CodeWeaver.cs:line 260
   at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in C:\TeamCity\BuildAgent\work\sc-11273\Level1\src\Starcounter.Weaver\CodeWeaver.cs:line 86
   --- End of inner exception stack trace ---
```
@per-samuelsson Do You know any, even temporary solution that We could use in this case for Website to be working at SC 2.4? Right now It's our highest priority issue.

**Comment by PatrykSzwer** [comment]
Seems like updating `Starcounter.Authorization.Library` to version 1.4 fixes this problem. The only (known) problem left is https://github.com/Starcounter/Home/issues/338.

**Comment by warpech** [comment]
https://github.com/Starcounter/Home/issues/338 is now fixed, so do we have problems with Starcounter 2.4 anymore? If not, @PatrykSzwer can you please make a release for Starcounter 2.3 and 2.4?

**Comment by PatrykSzwer** [comment]
Looks like we have all problems fixed and Website is now working correctly with Starcounter 2.4. About releases, WDYT how we should take care of simultaneous releases of Website app for SC 2.3 and 2.4? Should we create 2 separated releases/versions, one for 2.3 and second for 2.4? If yes then how version numbers should go?

**Comment by warpech** [comment]
I think there should be a single version number tagged in Website repo `master` branch. Make a Warehouse package of that branch for Starcounter 2.3.

Then merge `master` to `master-2.4` and make a Warehouse package of that branch for Starcounter 2.4. Warehouse should accept two different builds of the same app version if the build time is different.

**Comment by PatrykSzwer** [comment]
Website for both `master` and `master-2.4` was released. Closing.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/Website/releases/tag/4.1.0
