### ISSUE TITLE
Middleware does not handle response on first call

### ISSUE THREAD

**Issue by un-tone** [Starcounter/Website#286]
We have a middleware registered in the test helper app which add a cookie to responses.
In the test we call `new AcceptanceHelperOneMasterPage(Driver).Load()` but for some reason the middleware does not handle it. It do only in the second time so I've temporarily added the same second call. This issue did not appear when was not called first in a test fixture, i.e. if I move the test `MiddlewareHandlesResponse_CookieAdded` ([link](https://github.com/Starcounter/Website/pull/285/files#diff-604decb92d33fa63b2dd90b4f403643aR34)) below after `LoadEmptyJson_ExceptionReturned` ([link](https://github.com/Starcounter/Website/pull/285/files#diff-604decb92d33fa63b2dd90b4f403643aR56 )) the test passes well with only one call of `new AcceptanceHelperOneMasterPage(Driver).Load()`

**Comment by PatrykSzwer** [comment]
Moved to: https://github.com/Starcounter/Blending/issues/16
