### ISSUE TITLE
Add link to website tutorial video in Readme

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Website#287]
@warpech recorded pretty cool, explanatory video about basically every aspect of Website app. I think there is no cons in adding link to this video into readme so that every new user, who doesn't know about video, will see it right away. 

@warpech WDYT? Are there any arguments against this?

**Comment by warpech** [comment]
That's a very good idea, please do that.

**Comment by PatrykSzwer** [comment]
Done.
