### ISSUE TITLE
Data issues on a clean DB with SC 2.4

### ISSUE THREAD

**Issue by Mihaiii** [Starcounter/Website#295]
### Steps to reproduce
1. Use SC 2.4.0.4182
1. Delete db : `staradmin delete db --force`
2. Run website app on https://github.com/Starcounter/Website/commit/001ee1e0db12c7e1780afcb70811308565decddb (current latest for `master-2.4`)
3. Run Sign in app on https://github.com/StarcounterApps/SignIn/commit/74ae8817ed1a7e1b46b0f86dba4f0dabb13ec074 (current latest for `master-2.4`)
4. Run Composition Provider on https://github.com/Starcounter/CompositionProvider/commit/bfb10ef8568e876aeff9538f81dd4600db88fc01  (current latest for `master-2.4`)
5. Navigate to `http://localhost:8080/websiteeditor`

### Expected result
SignIn icon to be show.
### Actual result
SignIn icon is not shown.

Extra info:
- it works after `/websiteeditor/resetdata` is called
- even after the `/websiteeditor/resetdata` is called, if I go to `/websiteeditor/surface/{surface.Key}/general` (after I created an admin user and signed in) I don't get `/websiteeditor/help?topic={surface}`.

**Comment by PatrykSzwer** [comment]
Blending rules seems to be not connected with blending points, or at least are not shown in app. Even if we create a new one and refresh page, there will be no blending rules shown. More interesting fact is that after or before calling resetdata, blending points and rules in DB are the same, which is as expected since right after running app with fresh DB, website is basically calling same function which resetdata does.
cc @un-tone

**Comment by PatrykSzwer** [comment]
I think I found a problem.
Here's the situation in DB in 2.4.0:
![webmaps 24](https://user-images.githubusercontent.com/25042256/34006975-8049737a-e100-11e7-9b67-8c853fed38b7.PNG)
and here's 2.3.1:
![image](https://user-images.githubusercontent.com/25042256/34006999-90b36126-e100-11e7-9b5c-d2b100c373ad.png)
Seems like `ToWhat` and `Url` are messing.

**Comment by un-tone** [comment]
> Seems like ToWhat and Url are messing

@PatrykSzwer what do you mean

It looks like this does not work (`WebSection.cs`):
```csharp
public IEnumerable<WebMap> Maps => Db.SQL<WebMap>("SELECT wm FROM Simplified.Ring6.WebMap wm WHERE wm.Section = ?", this);
```

**Comment by PatrykSzwer** [comment]
Nvm, I though there is a difference in DB before and after `resetData` and deleting DB but I can't see any. I'm trying to understand what could make situation that after deleting DB and running website blending rule is not working, but after reseting data It does, even if there is theoretically no difference in behavior in both situations.

**Comment by PatrykSzwer** [comment]
BTW Am I the only one who's keep getting those errors about BindingInterfaces under 2.4 in VS? 
![image](https://user-images.githubusercontent.com/25042256/34036142-93cab362-e184-11e7-8b68-1eb901d3614f.png)

**Comment by PatrykSzwer** [comment]
I think I've stepped on something that could be a hint for a reason to this.
If You do following steps, It will work at newly created database:
1. Run `websiteprovider` in debug trough VS.
2. Place a breakpoint in line https://github.com/Starcounter/Website/blob/master-2.4/src/WebsiteProvider/Api/BlendingHandlers.cs#L93
3. Run websiteEditor.
4. Breakpoint will hit, first one should be the TopBar SignIn map. (I've changed data generation a little for testing purposes so I'm not sure if You also will have it catched first).
5. Just F10 couple of times to line with `locker.ExitWritelock();` and then just go with F5.
6. Run SignIn app.

You will see signIn mapped as It should be and is after resetdata. Seems like it can be somehow related to race condition.

**Comment by un-tone** [comment]
> BTW Am I the only one who's keep getting those errors about BindingInterfaces under 2.4 in VS?

I have this too.

**Comment by un-tone** [comment]
The problem is exactly in

```csharp
Db.SQL<WebMap>("SELECT wm FROM Simplified.Ring6.WebMap wm WHERE wm.Section = ?", this)
```

and that `Section`'s getter is `get { return this.WhatIs as WebSection; }`

For instance, if I use `WhatIs` instead of `Section` it works well:

```csharp
Db.SQL<WebMap>("SELECT wm FROM Simplified.Ring6.WebMap wm WHERE wm.WhatIs = ?", webSection)
```

**Comment by un-tone** [comment]
The problem is in Simplified on <https://www.nuget.org/packages/Starcounter.Simplified.Data.Model/>.
You should update it to the last version. The last NuGet package still uses SynonymousTo attribute but should not (https://github.com/StarcounterApps/Simplified/issues/95).

**Comment by un-tone** [comment]
I've checked it. All works well with last Simplified from `master-2.4` branch

**Comment by PatrykSzwer** [comment]
I've talked to @habib535 and He released new version of simplified nuget package based on current Simplified master branch. After Nuget will be done with indexing I'll update it and do the last check.

**Comment by PatrykSzwer** [comment]
I've pushed solution with updated package to v 1.0.3. Everything seems to be working correctly now.

Please have in mind that all other apps that uses `Simplified.Data.Model` package needs to have it updated, otherwise they wont run in same time with Website.
