### ISSUE TITLE
⏰ Upgrade the views to Polymer 2

### ISSUE THREAD

**Issue by warpech** [Starcounter/Website#297]
Since Polymer 2.0 is coming to Starcounter 2.4, we need to upgrade the views to use Polymer 2.0

**Comment by alshakero** [comment]
PR in https://github.com/Starcounter/Website/pull/299

**Comment by warpech** [comment]
Done in https://github.com/Starcounter/Website/pull/306

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/Website/releases/tag/4.2.0
