### ISSUE TITLE
Manage the window title

### ISSUE THREAD

**Issue by warpech** [Starcounter/Website#301]
After https://github.com/Starcounter/RebelsLounge/issues/232 is done, add a new feature to BlendingEditor and BlendingProvider to manage the window title.

On the surface general configuration page, it should be possible to manage the window title by providing a string. The string should allow using few variables:

- `{AppTitle}` - whatever value is resolved by `DisplayAppTitle` for the current session
- `{SurfaceName}` - the current surface name

The default value for the window title should be `{AppTitle} - {SurfaceName}`

Requested by @mmnosek in https://github.com/StarcounterFreezer/Launcher/issues/245

**Comment by mmnosek** [comment]
Doing this on the surface level is a very good idea. The question is, how to deal with application - dependent titles. For instance, following proposed scheme: `{AppTitle} - {SurfaceName}` we can have a page displaying details about some person. A title for such surface would be: `Starcounter Intranet - Person Details`. What if I would like to have a title specifically for the loaded person? Let's say: `Starcounter Intranet - Person Details - Warpech`?

Should apps be able to add something to this surface-specified title?

**Comment by warpech** [comment]
> A title for such surface would be: `Starcounter Intranet - Person Details`. What if I would like to have a title specifically for the loaded person? Let's say: `Starcounter Intranet - Person Details - Warpech`?

Not quite. A title for such surface would be `People - Starcounter Intranet`, because People is the app and Starcounter Intranet is the surface name.

People app can provide a custom title (different than just the app name) by setting in to the database for the current user session. There is a static method that makes that simpler: `Simplified.Ring6.SessionAppTitle.SetForCurrentSession()`.

If you want it completely custom then you would need to implement custom surfaces for each kind of page. You can make it DRY by nesting the "Starcounter Intranet" surface on another surface that has just one main blending point but a different title.

If this does not sound comprehensive enough then please provide a user story.

**Comment by PatrykSzwer** [comment]
Moved to: https://github.com/Starcounter/Blending/issues/14
