### ISSUE TITLE
Manage the favicon

### ISSUE THREAD

**Issue by warpech** [Starcounter/Website#302]
After https://github.com/Starcounter/RebelsLounge/issues/232 is done, add a new feature to BlendingEditor and BlendingProvider to manage the favicon.

On the surface general configuration page, it should be possible to manage the favicon by providing a URI to it. The media file can be uploaded using Images app.

Requested by @mmnosek in https://github.com/StarcounterFreezer/Launcher/issues/252

**Comment by PatrykSzwer** [comment]
Moved to: https://github.com/Starcounter/Blending/issues/13
