### ISSUE TITLE
Decorating surface blending points

### ISSUE THREAD

**Issue by warpech** [Starcounter/Website#303]
After https://github.com/Starcounter/RebelsLounge/issues/232

This proposal is intended as a step to make the GUI of BlendingEditor more powerful and the experience configuring the typical blending configurations more "point and click".

For the app responses that are placed in the blending points of a surface, there is commonly a need to do something more than just direct insertion of these responses to `starcounter-include`. It might be additional behavior or some specific look-and-feel:

i. highlight link to the current page using a CSS class ([issue](https://github.com/Starcounter/RebelsLounge/issues/53#issuecomment-262828532))
ii. autofocus the first form field, if no other element is explicitly focused ([issue](https://github.com/StarcounterApps/SignIn/issues/49))
ii. wrap responses in an expandable dropdown icon ([custom element in surface Shadow DOM](https://github.com/Starcounter/Website/blob/3ffdb91ab4d201e225d2d84d5d39e01e887b4077/src/WebsiteEditor/Content/HtmlCompositions/topbar-composition.html))

These things cannot really be part of the composition because we want them in all compositions inserted in a particular blending point.

In this proposal, I will call the above behaviors "decorating the blending point of a surface".

My goal is to make it user-friendly to apply such decorations by having:

1. built-in decorations that can be applied by point and click in the GUI
2. a page in docs that explains the pattern of writing own decorations in form of custom elements, similar to `<topbar-menu>` [here](https://github.com/Starcounter/Website/blob/3ffdb91ab4d201e225d2d84d5d39e01e887b4077/src/WebsiteEditor/Content/HtmlCompositions/topbar-composition.html).

To implement point 1, the built-in decorations would be implemented in one (modular) custom element that listens to the `stamped` event:

```js
{
  BlendingPoints: {
    TopLeft: {
      /* app responses go here */
      Launchpad: {..},
      BlendingProvider: {..}
   },
  },
  BlendingDecorations: {
    TopLeft: [
      {Name: "HighlightCurrentLink", Enabled: false, Config: []},
      {Name: "AutofocusFirstInput", Enabled: false, Config: []},
      {Name: "WrapInDropdown", Enabled: true, Config: [{Key: "icon", Value: "hamburger"}, {Key: "label", Value: "Menu"}]}
    ]
  }
}
```

```html
<template>
  <template is="dom-bind">
    <starcounter-include 
      view-model="{{model.BlendingPoints.TopLeft}}" 
      blending-decorations="{{model.BlendingDecorations.TopLeft}}" //this is not really a property of starcounter-include but metadata for blendingprovider-decorations
      slot="Website/topleft">
    </starcounter-include>
  </template>

  <template is="declarative-shadow-dom">
    <blendingprovider-decorations>
      <slot name="Website/topleft"></slot>
    </blendingprovider-decorations>
  </template>
</template>
```

This will allow us to have a GUI in BlendingEditor [that might look like this](https://docs.google.com/drawings/d/1H4DZwuPp9gP9MO-2kOPR6_C_Pw4VQxP5zDcQFfA8_LI/edit)

@tomalec WDYT?

-------

Edit: made the text clearer. [Old version](https://gist.github.com/warpech/90d1548582fc5125def69318476292dc)

**Comment by tomalec** [comment]
Sorry, I'm, afraid I'm not getting the picture :|

Could you describe/elaborate on 
1. what you mean by "the content wrapped by WebsiteProvider",
2. What do you mean by "a decorator"? What should it do and with what?,
3. Could you provide a view-model for your example, especially for `model.BlendingDecorations.Top`?
4. What is the "custom decorator" in https://github.com/Starcounter/Website/blob/3ffdb91ab4d201e225d2d84d5d39e01e887b4077/src/WebsiteEditor/Content/HtmlCompositions/topbar-composition.html? Whare it is defined and used?

**Comment by warpech** [comment]
I added some clarifications. Please read again.

**Comment by warpech** [comment]
Added few more clarifications to JSON.

**Comment by warpech** [comment]
Perhaps for the GUI, it would be better to call it "Behaviors".

**Comment by tomalec** [comment]
> These things cannot really be part of the composition because we want them in all compositions inserted in a particular blending point.

Why not? That's what composition is for.

> This will allow us to have a GUI in BlendingEditor that might look like this

This one scares me, as it moves us towards the path of Adobe CQ5, and forcing customers through a maze of an enormous configuration of a composition of ready-made specific elements that limits UI flexibility and expression like hell. And building UI using an editor that looks like this: https://helpx.adobe.com/content/dam/help/en/experience-manager/6-3/sites/developing/using/components-basics/_jcr_content/main-pars/procedure_1705577438/proc_par/step_10615122/step_par/image/screen_shot_2012-02-13at60457pm.png

I'd appreciate a meeting, as I still don't get why do we even need that, and why Shadow DOM compositions are not enough?

**Comment by PatrykSzwer** [comment]
Moved to https://github.com/Starcounter/Blending/issues/15
