### ISSUE TITLE
"Website Master-2.4 with Starcounter Develop (2.4)" build fails

### ISSUE THREAD

**Issue by warpech** [Starcounter/Website#304]
"Website Master-2.4 with Starcounter Develop (2.4)" build fails with an error:

```
[21:15:29]merge: origin/master-2.4 - not something we can merge
[21:15:29]Process exited with code 1
```

Example: https://teamcity.starcounter.org/viewLog.html?buildId=41622&buildTypeId=Apps_Website_WebsiteMaster24withStarcounterDevelop24&tab=buildLog

This is strange because the branch `master-2.4` definitely exists.

@joozek78 could you pls take a look on Tuesday?

**Comment by joozek78** [comment]
It seems that master-2.4 is just not fetched. We can just add "git fetch
origin master-2.4", but first I'd like to figure out why this worked before
o_O

**Comment by joozek78** [comment]
I've actually changed merge to pull. Works now
