### ISSUE TITLE
Remove viewport meta tag creation script from ResponsiveSurface.html

### ISSUE THREAD

**Issue by alshakero** [Starcounter/Website#308]
It's redundant now.

Lines of interest: https://github.com/Starcounter/Website/blob/70ad491f486fc2ad8c2e4c769f6fb65233fb5187/src/WebsiteProvider/wwwroot/WebsiteProvider/surfaces/ResponsiveSurface.html#L35-L42

More on this in this commit https://github.com/Starcounter/level1/commit/61e4eaaaa6607c07389505f77ab34ce1b8ed6849.

**Comment by PatrykSzwer** [comment]
This issue is moved to https://github.com/Starcounter/Blending/issues/7
