### ISSUE TITLE
Add Workspaces to the Website app

### ISSUE THREAD

**Issue by warpech** [Starcounter/Website#47]
@malx122 represents use case in which the DOM state of blending point should be retained as it was done in Workspaces in the old Launcher.

A similar functionality should be implemented in Website.

Ideally it should allow caching multiple responses from the same app, as well as configuring the caching limit.

**Comment by warpech** [comment]
I am aware that this requires more clarification before implementation. Assigning it to me for the time being.

**Comment by warpech** [comment]
Discussed today between me and @malx122, there are at least two use cases for workspaces:

1. They make it possible to immediately switch to a view that was seen before
2. They retain state (such as position of scrollbars)

@malx122 uses the `AutoRefreshBoundProperties == false`, so that the server does not observe and push changes for data bound to the inactive workspaces.

**Comment by tomalec** [comment]
What about Workspace micro app? That would provide a view, that could be blended into root,main area, any area, could blend in other apps responses, to keep them in the DOM instead of redirecting and track the scroll position.

**Comment by un-tone** [comment]
AFAIK a work on this issue was started (and maybe finished) but I can't find a branch with that code changes. I wanted to check it and try with last other changes in WebsiteProvider app.

**Comment by warpech** [comment]
I have pushed the proposed implementation. It needs careful review and testing with other apps (two tests are included).

I decided to rename the feature to "ViewKeeper". Hopefully that's more understandable?

**Comment by un-tone** [comment]
Closing as done.
For the View Keeper settings I created a separate issue https://github.com/Starcounter/Website/issues/268/
